# Generated by Django 3.2.3 on 2021-05-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='timestam',
            new_name='timestamp',
        ),
    ]
